final List<Map<String, dynamic>> posts = [
  {
    'id': 'p01',
    'title': '기숙사 간식 나눔해요!',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u01',
      'name': '28기 사용자1',
      'phone': '010-1210-4321',
      'kakao': 'https://open.kakao.com/o/sample1',
    },
    'category': ['음식', '교복'],
    'explanation': '과자, 음료 등 많이 있어요. 부담없이 가져가세요!',
    'items': [
      {
        'name': '음식 물품 1',
        'price': 0,
        'quantity': 5,
        'status': 'available',
        'buyerId': null,
        'sellerId': 'u01'
      },
      {
        'name': '음식 물품 2',
        'price': 2500,
        'quantity': 1,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u01'
      },
      {
        'name': '음식 물품 3',
        'price': 1000,
        'quantity': 3,
        'status': 'sold',
        'buyerId': 'u07',
        'sellerId': 'u01'
      },
      {
        'name': '음식 물품 4',
        'price': 0,
        'quantity': 1,
        'status': 'sold',
        'buyerId': 'u09',
        'sellerId': 'u01'
      },
      {
        'name': '음식 물품 5',
        'price': 3000,
        'quantity': 1,
        'status': 'available',
        'buyerId': 'u06',
        'sellerId': 'u01'
      },
      {
        'name': '음식 물품 6',
        'price': 500,
        'quantity': 4,
        'status': 'reserved',
        'buyerId': 'u03',
        'sellerId': 'u01'
      },
    ],
  },
  {
    'id': 'p02',
    'title': '수학 교재 팝니다',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u02',
      'name': '29기 사용자2',
      'phone': '010-1220-1234',
      'kakao': 'https://open.kakao.com/o/sample2',
    },
    'category': ['교재'],
    'explanation': '1학기 동안 사용한 책, 필기 깨끗합니다.',
    'items': [
      {
        'name': '교재 물품 1',
        'price': 2000,
        'quantity': 2,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u02'
      },
      {
        'name': '교재 물품 2',
        'price': 1000,
        'quantity': 1,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u02'
      },
      {
        'name': '교재 물품 3',
        'price': 2500,
        'quantity': 3,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u02'
      },
      {
        'name': '교재 물품 4',
        'price': 3000,
        'quantity': 2,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u02'
      },
      {
        'name': '교재 물품 5',
        'price': 1500,
        'quantity': 5,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u02'
      },
      {
        'name': '교재 물품 6',
        'price': 1500,
        'quantity': 1,
        'status': 'sold',
        'buyerId': 'u04',
        'sellerId': 'u02'
      },
    ],
  },
  {
    'id': 'p03',
    'title': '겨울 교복 나눔',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u03',
      'name': '30기 사용자3',
      'phone': '010-1230-5678',
      'kakao': 'https://open.kakao.com/o/sample3',
    },
    'category': ['교복'] ,
    'explanation': '겨울 점퍼랑 스커트 드릴게요. 세탁 완료!',
    'items': [
      {
        'name': '교복 물품 1',
        'price': 0,
        'quantity': 5,
        'status': 'reserved',
        'buyerId': 'u07',
        'sellerId': 'u03'
      },
      {
        'name': '교복 물품 2',
        'price': 500,
        'quantity': 4,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u03'
      },
      {
        'name': '교복 물품 3',
        'price': 3000,
        'quantity': 4,
        'status': 'available',
        'buyerId': 'u07',
        'sellerId': 'u03'
      },
      {
        'name': '교복 물품 4',
        'price': 2500,
        'quantity': 1,
        'status': 'available',
        'buyerId': 'u04',
        'sellerId': 'u03'
      },
      {
        'name': '교복 물품 5',
        'price': 3000,
        'quantity': 4,
        'status': 'available',
        'buyerId': 'u09',
        'sellerId': 'u03'
      },
    ],
  },
  {
    'id': 'p04',
    'title': '생활용품 정리',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u04',
      'name': '27기 사용자4',
      'phone': '010-1240-9876',
      'kakao': 'https://open.kakao.com/o/sample4',
    },
    'category': ['생활용품'],
    'explanation': '기숙사 정리하며 안 쓰는 생활용품 나눠요.',
    'items': [
      {
        'name': '생활용품 물품 1',
        'price': 1500,
        'quantity': 4,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u04'
      },
      {
        'name': '생활용품 물품 2',
        'price': 0,
        'quantity': 5,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u04'
      },
      {
        'name': '생활용품 물품 3',
        'price': 1000,
        'quantity': 2,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u04'
      },
      {
        'name': '생활용품 물품 4',
        'price': 0,
        'quantity': 2,
        'status': 'available',
        'buyerId': 'u03',
        'sellerId': 'u04'
      },
      {
        'name': '생활용품 물품 5',
        'price': 1000,
        'quantity': 2,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u04'
      },
    ],
  },
  {
    'id': 'p05',
    'title': '중간고사 대비 세트',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u05',
      'name': '31기 사용자5',
      'phone': '010-1250-5555',
      'kakao': 'https://open.kakao.com/o/sample5',
    },
    'category': ['교재'],
    'explanation': '과목별 예상문제 포함, 요점 정리 잘 되어 있음.',
    'items': [
      {
        'name': '교재 물품 1',
        'price': 2500,
        'quantity': 2,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u05',
      },
      {
        'name': '교재 물품 2',
        'price': 1000,
        'quantity': 1,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u05',
      },
      {
        'name': '교재 물품 3',
        'price': 2500,
        'quantity': 2,
        'status': 'reserved',
        'buyerId': 'u08',
        'sellerId': 'u05',
      },
      {
        'name': '교재 물품 4',
        'price': 500,
        'quantity': 2,
        'status': 'available',
        'buyerId': 'u06',
        'sellerId': 'u05',
      },
      {
        'name': '교재 물품 5',
        'price': 2000,
        'quantity': 3,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u05',
      },
      {
        'name': '교재 물품 6',
        'price': 2500,
        'quantity': 1,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u05',
      },
      {
        'name': '교재 물품 7',
        'price': 1500,
        'quantity': 3,
        'status': 'reserved',
        'buyerId': 'u05',
        'sellerId': 'u05',
      },
      {
        'name': '교재 물품 8',
        'price': 500,
        'quantity': 1,
        'status': 'available',
        'buyerId': 'u06',
        'sellerId': 'u05',
      },
      {
        'name': '교재 물품 9',
        'price': 1000,
        'quantity': 4,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u05',
      },
    ],
  },
  {
    'id': 'p06',
    'title': '붕어빵 팝니다 🐟',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u06',
      'name': '28기 사용자6',
      'phone': '010-1260-8888',
      'kakao': 'https://open.kakao.com/o/sample6',
    },
    'category': ['음식'],
    'explanation': '팥/슈크림 있어요. 따끈할 때 챗 주세요!',
    'items': [
      {
        'name': '음식 물품 1',
        'price': 1500,
        'quantity': 3,
        'status': 'available',
        'buyerId': 'u07',
        'sellerId': 'u06',
      },
      {
        'name': '음식 물품 2',
        'price': 1000,
        'quantity': 3,
        'status': 'available',
        'buyerId': 'u01',
        'sellerId': 'u06',
      },
      {
        'name': '음식 물품 3',
        'price': 1500,
        'quantity': 3,
        'status': 'available',
        'buyerId': 'u02',
        'sellerId': 'u06',
      },
      {
        'name': '음식 물품 4',
        'price': 1000,
        'quantity': 5,
        'status': 'sold',
        'buyerId': 'u02',
        'sellerId': 'u06',
      },
      {
        'name': '음식 물품 5',
        'price': 3000,
        'quantity': 1,
        'status': 'available',
        'buyerId': 'u01',
        'sellerId': 'u06',
      },
      {
        'name': '음식 물품 6',
        'price': 1500,
        'quantity': 2,
        'status': 'reserved',
        'buyerId': 'u05',
        'sellerId': 'u06',
      },
      {
        'name': '음식 물품 7',
        'price': 3000,
        'quantity': 5,
        'status': 'sold',
        'buyerId': 'u09',
        'sellerId': 'u06',
      },
    ],
  },
  {
    'id': 'p07',
    'title': '남은 교복 저렴히 정리',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u07',
      'name': '29기 사용자7',
      'phone': '010-1270-1111',
      'kakao': 'https://open.kakao.com/o/sample7',
    },
    'category': ['교복', '생활용품'],
    'explanation': '상의 2벌, 치마 1벌 있습니다. 상태 깨끗해요.',
    'items': [
      {
        'name': '교복 물품 1',
        'price': 500,
        'quantity': 3,
        'status': 'reserved',
        'buyerId': 'u02',
        'sellerId': 'u07',
      },
      {
        'name': '교복 물품 2',
        'price': 1500,
        'quantity': 2,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u07',
      },
      {
        'name': '교복 물품 3',
        'price': 3000,
        'quantity': 3,
        'status': 'sold',
        'buyerId': 'u04',
        'sellerId': 'u07',
      },
      {
        'name': '교복 물품 4',
        'price': 1500,
        'quantity': 2,
        'status': 'available',
        'buyerId': null,
        'sellerId': 'u07',
      },
      {
        'name': '교복 물품 5',
        'price': 3000,
        'quantity': 2,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u07',
      },
      {
        'name': '교복 물품 6',
        'price': 0,
        'quantity': 2,
        'status': 'sold',
        'buyerId': 'u03',
        'sellerId': 'u07',
      },
    ],
  },
  {
    'id': 'p08',
    'title': '방 청소하다가 나온 것들',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u08',
      'name': '30기 사용자8',
      'phone': '010-1280-2222',
      'kakao': 'https://open.kakao.com/o/sample8',
    },
    'category': ['생활용품'],
    'explanation': '필요한 분 있으시면 가져가세요.',
    'items': [
      {
        'name': '생활용품 물품 1',
        'price': 2000,
        'quantity': 5,
        'status': 'available',
        'buyerId': null,
        'sellerId': 'u08',
      },
      {
        'name': '생활용품 물품 2',
        'price': 2000,
        'quantity': 3,
        'status': 'available',
        'buyerId': null,
        'sellerId': 'u08',
      },
      {
        'name': '생활용품 물품 3',
        'price': 2000,
        'quantity': 2,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u08',
      },
      {
        'name': '생활용품 물품 4',
        'price': 500,
        'quantity': 1,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u08',
      },
      {
        'name': '생활용품 물품 5',
        'price': 1000,
        'quantity': 1,
        'status': 'reserved',
        'buyerId': 'u09',
        'sellerId': 'u08',
      },
      {
        'name': '생활용품 물품 6',
        'price': 0,
        'quantity': 2,
        'status': 'available',
        'buyerId': 'u09',
        'sellerId': 'u08',
      },
      {
        'name': '생활용품 물품 7',
        'price': 500,
        'quantity': 2,
        'status': 'sold',
        'buyerId': 'u09',
        'sellerId': 'u08',
      },
      {
        'name': '생활용품 물품 8',
        'price': 0,
        'quantity': 4,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u08',
      },
    ],
  },
  {
    'id': 'p09',
    'title': '초코 간식 세트',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u09',
      'name': '27기 사용자9',
      'phone': '010-1290-3333',
      'kakao': 'https://open.kakao.com/o/sample9',
    },
    'category': ['음식'],
    'explanation': '달달한 거 좋아하시는 분에게 추천!',
    'items': [
      {
        'name': '음식 물품 1',
        'price': 2000,
        'quantity': 4,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u09',
      },
      {
        'name': '음식 물품 2',
        'price': 500,
        'quantity': 5,
        'status': 'available',
        'buyerId': 'u09',
        'sellerId': 'u09',
      },
      {
        'name': '음식 물품 3',
        'price': 0,
        'quantity': 4,
        'status': 'sold',
        'buyerId': 'u01',
        'sellerId': 'u09',
      },
      {
        'name': '음식 물품 4',
        'price': 2000,
        'quantity': 1,
        'status': 'reserved',
        'buyerId': 'u10',
        'sellerId': 'u09',
      },
      {
        'name': '음식 물품 5',
        'price': 2000,
        'quantity': 2,
        'status': 'available',
        'buyerId': null,
        'sellerId': 'u09',
      },
      {
        'name': '음식 물품 6',
        'price': 2500,
        'quantity': 5,
        'status': 'reserved',
        'buyerId': null,
        'sellerId': 'u09',
      },
      {
        'name': '음식 물품 7',
        'price': 2500,
        'quantity': 1,
        'status': 'sold',
        'buyerId': 'u07',
        'sellerId': 'u09',
      },
    ],
  },
  {
    'id': 'p10',
    'title': '졸업하면서 정리합니다',
    'image': 'https://via.placeholder.com/150',
    'user': {
      'id': 'u10',
      'name': '31기 사용자10',
      'phone': '010-1300-4444',
      'kakao': 'https://open.kakao.com/o/sample10',
    },
    'category': ['교재'],
    'explanation': '전공서적 위주로 드려요. 필요하신 분 챗!',
    'items': [
      {
        'name': '교재 물품 1',
        'price': 2000,
        'quantity': 5,
        'status': 'available',
        'buyerId': 'u03',
        'sellerId': 'u10',
      },
      {
        'name': '교재 물품 2',
        'price': 0,
        'quantity': 3,
        'status': 'sold',
        'buyerId': null,
        'sellerId': 'u10',
      },
      {
        'name': '교재 물품 3',
        'price': 2000,
        'quantity': 2,
        'status': 'available',
        'buyerId': 'u05',
        'sellerId': 'u10',
      },
      {
        'name': '교재 물품 4',
        'price': 1500,
        'quantity': 5,
        'status': 'available',
        'buyerId': 'u08',
        'sellerId': 'u10',
      },
      {
        'name': '교재 물품 5',
        'price': 0,
        'quantity': 2,
        'status': 'reserved',
        'buyerId': 'u07',
        'sellerId': 'u10',
      },
      {
        'name': '교재 물품 6',
        'price': 2500,
        'quantity': 2,
        'status': 'available',
        'buyerId': null,
        'sellerId': 'u10',
      },
    ],
  },
];
